stages:
  - deploy
  - cleanup

include:
  - component: $CI_SERVER_FQDN/components/docker/deploy@~latest
    inputs:
      app_volume: "/mnt/system/apps/ollama"
      app_name_in_vault: "ollama"
      variables_in_vault: "OAUTH_CLIENT_ID OAUTH_CLIENT_SECRET WEBUI_SECRET_KEY"
      reset_before_deploy: true

  - component: $CI_SERVER_FQDN/components/docker/cleanup@~latest
